# Site settings
title: 121.academy | Grab Teachers for Career Success 
description: "Online one-to-one learning platform"
baseurl: "" # the subpath of your site, e.g. /blog
url: "121.academy" # the name of your domain
logo_url: svg/121.academy.logo.svg # svg/min/logo.svg

# Hero
hero: 
    hero_img: adult-application-asian-733856.jpg # hero.jpg
    hero_title: 121.academy
    hero_description: Online one-to-one learning platform.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: xxx xx xxx
    emergency: xxx xx xxx
    email: contact@121.academy
    address: Sukhumwit<br/> Bangkok - Thailand

# Opening hours
monday_friday: 6:00 – 21:00
saturday: 10:00 – 21:00
sunday: 10:00 – 21:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Von schroeders 273, Viña del mar, Chile
    address_details: svg/min/logo.svg

# Social settings
facebook: https://www.facebook.com/121academy-158804261468795/
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2015 DentistSmile - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: UA-117360575-1
google_verification:
